// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternating_slice: dynamic(() => import("./AlternatingSlice")),
  big_text_slice: dynamic(() => import("./BigTextSlice")),
  can_diver: dynamic(() => import("./CanDiver")),
  carousel_slice: dynamic(() => import("./CarouselSlice")),
  hero: dynamic(() => import("./Hero")),
};
